---
- block:
    - name: Copy docker-compose
      copy:
        src: ../files/downloader
        dest: ~/stacks/
    
    - name: Create config directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/appdata/transmission
        - ~/appdata/pyload

    - name: Get transmission settings
      get_url: 
        url: https://raw.githubusercontent.com/aGhosh02/ansible-proxmox/master/roles/docker/files/downloader/settings.json
        dest: ~/appdata/transmission/settings.json

    - name: Downloader Setup
      shell: cd ~/stacks/downloader && docker-compose up -d