---
- block:
    - name: Copy docker-compose
      copy:
        src: ../files/ghostfolio
        dest: ~/stacks/
    
    - name: Create config directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/appdata/ghostfolio
    
    - name: Copy homeassistant config
      copy:
        src: /mnt/hdd1tb/Backup/appdata/{{item}}
        dest: ~/appdata/{{item}}
        remote_src: yes
      loop:
        - ghostfolio
    
    - name: Ghostfolio Setup
      shell: cd ~/stacks/ghostfolio && docker-compose up -d