---
- block:
    - name: Copy docker-compose
      copy:
        src: ../files/homeassistant
        dest: ~/stacks/
    
    - name: Create config directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/appdata/homeassistant
    
    - name: Copy homeassistant config
      copy:
        src: /mnt/hdd1tb/Backup/appdata/homeassistant/
        dest: ~/appdata/homeassistant/
        remote_src: yes
        
    - name: Homeassistant Setup
      shell: cd ~/stacks/homeassistant && docker-compose up -d