---
- block:
    - name: Copy docker-compose
      copy:
        src: ../files/media-centre
        dest: ~/stacks/
    
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      ansible.builtin.unarchive:
        src: https://github.com/aGhosh02/ansible-proxmox/raw/master/roles/docker/files/media-centre/sonarr.zip
        dest: ~/appdata/sonarr
        remote_src: yes

    - name: Media centre Setup
      shell: cd ~/stacks/media-centre && docker-compose up -d