---
- block:
    - name: Copy docker-compose
      copy:
        src: ../files/media-centre
        dest: ~/stacks/
    
    - name: Create config directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/appdata/bazarr
        - ~/appdata/jellyfin
        - ~/appdata/prowlarr
        - ~/appdata/radarr
        - ~/appdata/sonarr
    
    - name: Download/unarchive Bazarr config
      unarchive:
        src: http://10.0.100.3:8181/api/public/dl/GBZoLwno
        dest: ~/appdata/bazarr
        remote_src: yes
    
    - name: Download/unarchive Jellyfin config
      unarchive:
        src: http://10.0.100.3:8181/api/public/dl/bUlWrXzf
        dest: ~/appdata/jellyfin
        remote_src: yes
    
    - name: Download/unarchive Prowlarr config
      unarchive:
        src: http://10.0.100.3:8181/api/public/dl/kVckGEYH
        dest: ~/appdata/prowlarr
        remote_src: yes
    
    - name: Download/unarchive Radarr config
      unarchive:
        src: http://10.0.100.3:8181/api/public/dl/YBBBZhui
        dest: ~/appdata/radarr
        remote_src: yes
    
    - name: Download/unarchive Sonarr config
      unarchive:
        src: http://10.0.100.3:8181/api/public/dl/wf-jfnWl
        dest: ~/appdata/sonarr
        remote_src: yes

    - name: Media centre Setup
      shell: cd ~/stacks/media-centre && docker-compose up -d