---
- block:
    - name: Copy docker-compose
      copy:
        src: ../files/media-centre
        dest: ~/stacks/
    
    - name: Download *arr settings
      get_url:
        url: https://drive.google.com/file/d/1AvAAtcyhdjZ0hiufC1_vQHRVxmLqGUSl/view?usp=drive_link
        dest: ~/appdata/
    
    - name: Unzip config
      shell: cd ~/appdata/ && tar -xf configbackup.tar.xz

    - name: Media centre Setup
      shell: cd ~/stacks/media-centre && docker-compose up -d