---
- block:
    - name: Copy docker-compose
      copy:
        src: ../files/media-centre
        dest: ~/stacks/
    
    - name: Copy homeassistant config
      copy:
        src: /mnt/hdd1tb/Backup/appdata/{{item}}
        dest: ~/appdata/{{item}}
        remote_src: yes
      loop:
        - bazarr
        - jellyfin
        - prowlarr
        - radarr
        - sonarr

    - name: Media centre Setup
      shell: cd ~/stacks/media-centre && docker-compose up -d
    
    - name: Add prowlarr fix cron
      cron:
        name: "Fix Prowlarr links"
        special_time: daily
        job: "python3 ~/stacks/media-centre/prowlarr.py"