---
- block:
    - name: Copy docker-compose
      copy:
        src: ../files/photoprism
        dest: ~/stacks/
    
    - name: Create config directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/appdata/database

    - name: Photoprism Setup
      shell: cd ~/stacks/photoprism && docker-compose up -d
    
    - name: Reindex Photos
      shell: docker exec -d photoprism photoprism index -f
      when: trigger_reindex == true