---
- block:
    - name: Copy docker-compose
      copy:
        src: ../files/utils
        dest: ~/stacks/
    
    - name: Create config directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/appdata/homarr
        - ~/appdata/filebrowser

    - name: Utils Setup
      shell: cd ~/stacks/utils && docker-compose up -d