version: "3.9"
services:
  ghostfolioredis:
    image: redis
    container_name: redis
    networks:
      - ghostfolio_internal
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    user: ${PGID}:${PUID}
    environment:
      - TZ=${TZ}
    ports:
      - 6379:6379
    volumes:
      - ${APPDATA}/ghostfolio/redis:/data
    restart: unless-stopped

  ghostfoliodb:
    image: postgres:15
    container_name: postgres
    networks:
      - ghostfolio_internal
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "ghostfoliodb", "-U", "ghostfoliouser"]
      timeout: 45s
      interval: 10s
      retries: 10
    user: ${PGID}:${PUID}
    volumes:
      - ${APPDATA}/ghostfolio/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ghostfolioprod
      - POSTGRES_USER=ghostfoliouser
      - POSTGRES_PASSWORD=ghostfoliopass
    ports:
      - 5432:5432
    restart: unless-stopped

  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    container_name: ghostfolio
    networks:
      - ghostfolio_internal
      - ghostfolio_external
    environment:
      - NODE_ENV=production
      - ACCESS_TOKEN_SALT=0029cbdf-6895-4fca-9b33-b7d7530d449c
      - JWT_SECRET_KEY=0029cbdf-6895-4fca-9b33-b7d7530d449c
      - REDIS_HOST=ghostfolioredis
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://ghostfoliouser:ghostfoliopass@ghostfoliodb:5432/ghostfolioprod?sslmode=prefer
    ports:
      - 8435:3333
    restart: always
    depends_on:
      ghostfoliodb:
        condition: service_started
      ghostfolioredis:
        condition: service_healthy
networks:
  ghostfolio_internal:
    internal: true
  ghostfolio_external:
    internal: false