version: "3"
services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    networks:
      - homeassistant_internal
      - homeassistant_external
    volumes:
      - ${APPDATA}/homeassistant/config:/config
    ports:
      - 8123:8123
    restart: unless-stopped
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    networks:
      - homeassistant_internal
      - homeassistant_external
    volumes:
      - ${APPDATA}/homeassistant/mqtt:/config
    ports:
      - 1883:1883
    restart: unless-stopped
networks:
  homeassistant_internal:
    internal: true
  homeassistant_external:
    internal: false